//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<int> curse { get; set; }
        public Nullable<int> batch { get; set; }
        public string nic { get; set; }
        public Nullable<int> techno { get; set; }
    
        public virtual Batch Batch1 { get; set; }
        public virtual Course Course { get; set; }
    }
}
